FROM node:16-alpine
WORKDIR /usr/share/easybsb

RUN apk add nginx nginx-debug bash tini

COPY ./docker/local.sh /start.sh
RUN chmod +x /start.sh

ENTRYPOINT ["/sbin/tini", "--"]
CMD [ "bash", "/start.sh" ]
